services:
  mosquitto:
    image: eclipse-mosquitto
    ports:
      - "18883:1883"
    volumes:
      - ${HM_DATA_DIR}/mqtt_config:/mosquitto/config
    restart: unless-stopped
    
  webui:
    build: .
    depends_on:
      - mosquitto
    ports:
      - "19033:19033"
    volumes:
      - ${HM_DATA_DIR}/config.json:/app/config.json
      - ${HM_DATA_DIR}/templates:/app/templates
    restart: unless-stopped
    environment:
      - PYTHONUNBUFFERED=1
    command: python app.py